import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css'
import LangContextProvider from "@/lang.context";
import ThemeContextProvider from "@/theme.context";
import { Toaster } from "react-hot-toast";
import Providers from "@/Providers/QueryProvider";
import AuthSessionProvider from "@/Providers/AuthSessionProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Z-flux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ThemeContextProvider>
        <LangContextProvider>
        <AuthSessionProvider>
          <Toaster/>
          <Providers>
        {children}
        </Providers>
        </AuthSessionProvider>
        </LangContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
